@component('mail::message')
# CHF INVOICE GENERATED

Dear Initiator,

You are receiving this email because there is a new invoice generated at {{$payment->coe->coe_name}}

<h3>INVOICE DETAILS:</h3>

Generated by: {{$payment->cmd->last_name}} {{ $payment->cmd->first_name }}

Being billing invoice for: {{ $payment->start_date }} through {{$payment->end_date}}

Invoice generated on: {{$payment->cmd_approved_on}}

@component('mail::button', ['url' => 'https://chf.emgeresources.com/dashboard'])
Go to CHF Portal
@endcomponent

Thanks,<br>
    CHF Team.
@endcomponent
